name: pytorch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - scikit-learn
  - tqdm
  - tensorboardx
  - pandas
  - matplotlib
  - nbclassic
  - conda
  - scikit-image
  - dill
  - ipywidgets
  - jupyterlab_widgets
  - numba
  - ipykernel
  - jupyter_server
  - jupyterlab_server
  - wrapt
  - gcc
  - keras
  - jupyter_client
  - jupyter_core
  - jupyter-lsp
  - jupyter_events
  - jupyter_server_terminals
  - jupyterlab_pygments
  - lightning
  - ipython_genutils
  - pip
  - pip:
      - tensorflow==2.11
      - torch==2.2.0
      - torchvision==0.17.0
